/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes1;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Random;
/**
 *
 * @author pauhd
 */
public class GamePanel extends javax.swing.JPanel implements KeyListener, ActionListener  {

    private Ventana1 frame;
    Timer timerMovimiento;   // TEMPORIZADOR 1
    Timer timerSpawn;        // TEMPORIZADOR 2
    
    ArrayList<Frutas> frutas = new ArrayList<>();
    int cestaX = 350;
    int puntos = 0;
    int vidas = 3;
    Random r = new Random();
    
    public GamePanel(Ventana1 frame) {
        this.frame = frame;
        
        setLayout(null);
        setBackground(Color.black);
        setFocusable(true);
        addKeyListener(this);

        timerMovimiento = new Timer(15, this);
        timerSpawn = new Timer(800, e -> spawnStar());
    }
    
    public void startGame() {
        frutas.clear();
        cestaX = 350;
        puntos = 0;
        vidas = 3;

        timerMovimiento.start();
        timerSpawn.start();
        requestFocusInWindow();
    }
    
    public void spawnStar() {
        int x = r.nextInt(getWidth() - 40);
        frutas.add(new Frutas(x, 0));
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        moverEstrellas();
        repaint();
    }

    public void moverEstrellas() {
        ArrayList<Frutas> eliminar = new ArrayList<>();

        for (Frutas s : frutas) {
            s.y += s.vel;

            // colisión con cesta
            Rectangle cestaRect = new Rectangle(cestaX, 500, 100, 20);

            if (s.getBounds().intersects(cestaRect)) {
                puntos++;
                eliminar.add(s);
            }

            // si cae al fondo
            if (s.y > getHeight()) {
                vidas--;
                eliminar.add(s);
            }

            if (vidas <= 0) {
                timerMovimiento.stop();
                timerSpawn.stop();
                JOptionPane.showMessageDialog(this, "Fin de partida\nPuntos: " + puntos);
                frame.showMenu();
            }
        }

        frutas.removeAll(eliminar);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // cesta
        g.setColor(Color.white);
        g.fillRect(cestaX, 500, 100, 20);

        // estrellas
        for (Frutas s : frutas) {
            s.draw(g);
        }

        // HUD
        g.setColor(Color.white);
        g.setFont(new Font("SansSerif", Font.BOLD, 18));
        g.drawString("Puntos: " + puntos, 20, 30);
        g.drawString("Vidas: " + vidas, 20, 60);
    }

    // Controles
    @Override
    public void keyPressed(KeyEvent e) {
        int code = e.getKeyCode();
        if (code == KeyEvent.VK_LEFT && cestaX > 0) cestaX -= 20;
        if (code == KeyEvent.VK_RIGHT && cestaX < getWidth() - 100) cestaX += 20;
    }

    @Override public void keyReleased(KeyEvent e) {}
    @Override public void keyTyped(KeyEvent e) {}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
